import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
from dotenv import load_dotenv
import json

# credentials are configured using environment variables (loaded from dotenv)
# NOTE: credentials are generated by configuring an app on the spotify developer portal website.
load_dotenv()  # take environment variables from .env.
spotify = spotipy.Spotify(client_credentials_manager=SpotifyClientCredentials())

song_id = "spotify:track:3R9j8urSPiBbapNbyuSYkE"

# get track info (artist, album, etc)
#song = spotify.track(song_id)
# print(json.dumps(song))

# get things like tempo, key, energy, etc.
song = spotify.audio_features([song_id])
print(json.dumps(song))

