import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
from dotenv import load_dotenv
import pandas as pd
import seaborn
from matplotlib import pyplot as plt

# credentials are configured using environment variables (loaded from dotenv)
# NOTE: credentials are generated by configuring an app on the spotify developer portal website.
load_dotenv()  # take environment variables from .env.
spotify = spotipy.Spotify(client_credentials_manager=SpotifyClientCredentials())

playlist_id = "spotify:user:1241210207:playlist:1HRvOl0ZFbBqYdaoFBqoQi"

items = []
result = spotify.playlist_items(playlist_id, limit=5)
items = items + result['items']
while result['next']:
    result = spotify.next(result)
    items = items + result['items']


# might need to chunk this if len(items) > audio_features limit
songs = spotify.audio_features(list(map(lambda i: i['track']['uri'],items)))
for index,song in enumerate(songs):
    song['playlist_position'] = index + 1

df = pd.DataFrame(data=songs)

plot = seaborn.lineplot(x="playlist_position", y="valence",
             data=df)
plt.show()

