import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
from dotenv import load_dotenv
import json

# credentials are configured using environment variables (loaded from dotenv)
# NOTE: credentials are generated by configuring an app on the spotify developer portal website.
load_dotenv()  # take environment variables from .env.
spotify = spotipy.Spotify(client_credentials_manager=SpotifyClientCredentials())

playlist_id = "spotify:user:1241210207:playlist:1HRvOl0ZFbBqYdaoFBqoQi"

items = []
result = spotify.playlist_items(playlist_id, limit=5)
items = items + result['items']
while result['next']:
    result = spotify.next(result)
    items = items + result['items']


for item in items:
    track_uri = item['track']['uri']
    print(track_uri)


# print(json.dumps(items[0]))


# maybe this wont work unless I'm auth'd as a user and not an app.
# items = []
# result = spotify.current_user_saved_tracks(limit=50)
# items = items + result['items']
# while result['next']:
#     result = spotify.next(result)
#     items = items + result['items']

# print(len(items))
